### ISSUE TITLE
Application Not Starting

### ISSUE THREAD

**Issue by ccoughenour08** [bitwalker/distillery-aws-example#16]
Good Afternoon @bitwalker - 

The recent merge looks to have resolved all build issues. Once the application deploys, it isn't starting up. If you attempt to access the output URL, you will receive a 502 Error. If you trace from the ELB through to the EC2 instances, you will see that your target group doesn't have any valid instances. The health check, to check at port 4000, isn't successful.

If you log onto either ec2 instance, you can check for applications listening on port 4000, and nothing is there:

sudo lsof -i -P -n | grep LISTEN

Currently trying to debug the issue, it doesn't look like erlang is installed on the EC2 instance when I try to run the start script. There isn't a clear area where the original start logging was. If you get a moment, could you deploy and see if you see the same behaviour? 

Thanks,
C Luke Coughenour

**Comment by ccoughenour08** [comment]
@bitwalker Just an update, I believe the CodePipeline _thinks_ everything has started okay, but infact there is an erl_dump file in the /opt/apt directory showing issues.

`Wed Apr 29 17:19:02 2020
Slogan: Kernel pid terminated (application_controller) ({application_start_failure,distillery_example,{{shutdown,{failed_to_start_child,'Elixir.Cluster.Supervisor',{shutdown,{failed_to_start_child,example,{#{
System version: Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
Compiled: Tue Apr 28 11:05:12 2020`

**Comment by sfairchild** [comment]
I am also see the same behaviour when trying to deploy. I also tried to start the app locally but when trying to setup the DB with `mix ecto.create` I am getting some connection errors.

```
16:29:15.761 [error] GenServer #PID<0.408.0> terminating
** (ArgumentError) expected :hostname, :socket_dir, or :socket to be given
    (postgrex 0.15.3) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex 0.15.3) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection 2.2.1) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.10) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Example.Repo couldn't be created: killed
```

**Comment by caike** [comment]
For those running into issues running the application, I've submitted the fixes on this PR https://github.com/bitwalker/distillery-aws-example/pull/17

**Comment by bitwalker** [comment]
Those fixes have been merged, so I'll close this for now. If anything else comes up, please open a new issue.
